title: Lung Cancer Detection
description: Classify CT scan images using deep learning to detect whether patient is having cancer or not
about:


  This is a Lung Cancer Detector that detects if CT scan is of normal, malignant or benign tumor patient using Deep Learning and was built with [fastai](docs.fast.ai)


  This project was built by Amol and Pranav


  The web application was based on computer vision techniques.


code: https://github.com/tmabraham/retinopathy-classifier

sampleImages:
  - name: No Retinopathy
    url: https://i.imgur.com/bag6XaA.jpg
  - name: Mild Nonproliferative Retinopathy
    url: https://i.imgur.com/ZcLBb6b.jpg
  - name: Moderate Nonproliferative Retinopathy
    url: https://i.imgur.com/gLTumUd.jpg
  - name: Severe Nonproliferative Retinopathy
    url: https://i.imgur.com/Uw0rR4Y.jpg
  - name: Proliferative Diabetic Retinopathy
    url: https://i.imgur.com/TDUlmUa.jpg